device: "cuda"
EnvIdex: 0
write: false
render: false
load_model: false
eval_model: false
save_model: false
seed: 0
T_horizon: 2048
Distribution: "Beta"
Max_train_steps: 1000000
save_interval: 300000
eval_interval: 5000
gamma: 0.99
lambd: 0.95
clip_rate: 0.2
K_epochs: 10
net_width: 128
net_layer: 1
a_lr: 2e-5
c_lr: 2e-5
b_lr: 2e-4
g_lr: 2e-4
r_lr: 2e-4
l2_reg: 1e-3
a_optim_batch_size: 64
c_optim_batch_size: 64
entropy_coef: 0.001
entropy_coef_decay: 0.99
robust: false
noise: false
std: 0.0
delta: 0.0
