# @package _global_

# ContinuousCartPole environment config
# Baseline Reward: 500 (perfect score, zero-std)
env_name: ContinuousCartPole
env_index: 1
max_train_steps: 20000 # Offline learning: 20k
#max_train_steps: 200000 # Continual learning: 200k
explore_episode: 50
update_every: 10