# @package _global_

# LunarLanderContinuous environment config
env_name: LunarLanderContinuous-v3
env_index: 2
max_train_steps: 500000
net_arch: [400,300]
net_layer: 1
a_lr: 0.0001  # 1e-4
c_lr: 0.0001 # 1e-4
b_lr: 0.0005 # 5e-5
g_lr: 0.0005 # 5e-4
r_lr: 0.00005 # 5e-5
l2_reg: 0.0 # 1e-3 try