# @package _global_

# Pendulum environment config
env_name: Pendulum-v1
env_index: 0
max_train_steps: 50000
net_arch: [256,256]
net_layer: 1
a_lr: 0.005 # 5e-3
c_lr: 0.00005 # 5e-5
b_lr: 0.00005 # 5e-5
g_lr: 0.0005 # 5e-4
r_lr: 0.00005 # 5e-5
l2_reg: 0.001 # 1e-3