# @package _global_

# Pendulum environment config
# Benchmark Reward: -150
env_name: Pendulum-v1
env_index: 0
max_train_steps: 20000
net_arch: [256,256]
net_layer: 1
a_lr: 0.0005 # 5e-4
c_lr: 0.0005 # 5e-4
b_lr: 0.00005 # 5e-5
g_lr: 0.00005 # 5e-5
r_lr: 0.00005 # 5e-5
l2_reg: 0.01 # 1e-3