# @package _global_

env_name: HalfCheetah-v5
env_index: 4
eval_freq: 1000
eval_interval: 1000
save_interval: 1000
max_trn_steps: 100000
max_vae_trn_step: 10000

# Adam stepsize*
adam_lr: 1e-3
# learning rate of actor
actor_lr: 8e-4
critic_lr: 8e-4

vmin: -500