# @package _global_

# ContinuousCartPole environment config
# Baseline Reward: 500 (perfect score, zero-std)
env_name: ContinuousCartPole
env_index: 1
max_train_steps: 50000 # Offline learning: 20k
#max_train_steps: 200000 # Continual learning: 200k
a_lr: 0.005 # 5e-4
c_lr: 0.0001 # 5e-4