# @package _global_

# ContinuousCartPole environment config
# Baseline Reward: 500 (perfect score, zero-std)
env_name: ContinuousCartPole
env_index: 1
max_train_steps: 20000 # Offline learning: 20k
#max_train_steps: 200000 # Continual learning: 200k
a_lr: 0.005
c_lr: 5.0e-05