# @package _global_

# HalfCheetah environment config
# Benchmark Reward: 6000, std: 150
env_name: HalfCheetah-v5
env_index: 4
max_train_steps: 250000 
n_critic: 10
net_layer: 2
latent_dim: 10
robust_update_after: 50000
a_lr: 0.0003  
c_lr: 0.0003 
b_lr: 0.0005 
g_lr: 0.00005 
r_lr: 0.0005 