# @package _global_

env_name: Hopper-v5
env_index: 5
n_critic: 10
max_train_steps: 500000 
vae_steps: 50000
eval_interval: 5000
net_layer: 2
a_lr: 0.0003 
c_lr: 0.0003 
b_lr: 0.0005 # 5e-5
g_lr: 0.00005 # 5e-4
r_lr: 0.0005 # 5e-5