# @package _global_

# LunarLanderContinuous environment config
# Benchmark Reward: 250, std: 25
env_name: LunarLanderContinuous-v3
env_index: 2
max_train_steps: 250000 # 500k
robust_update_after: 20000
a_lr: 0.0001 # 5e-4
c_lr: 0.0001 # 5e-4
b_lr: 0.0005 # 5e-5
g_lr: 0.0005 # 5e-4
r_lr: 0.0005 # 5e-4