# @package _global_

env_name: Reacher-v5
env_index: 6
max_train_steps: 250000
n_critic: 2
alpha: 0.00001
adaptive_alpha: false
a_lr: 0.0003
c_lr: 0.0003 
b_lr: 0.0005 # 5e-5
g_lr: 0.0005 # 5e-4
r_lr: 0.00005 # 5e-5