# @package _global_

# HalfCheetah environment config
# Benchmark Reward: 6000, std: 150
env_name: HalfCheetah-v5
env_index: 4
max_train_steps: 400000 
n_critic: 5
a_lr: 0.0001  # Continual: 1e-4
c_lr: 0.0001 # Continual: 1e-4
b_lr: 0.0005 # 5e-5
g_lr: 0.0005 # 5e-4
r_lr: 0.00005 # 5e-5
l2_reg: 0.0 